### ISSUE TITLE
Create standalone Docker container for running QCrBoxTools commands

### ISSUE THREAD

**Issue by maxalbert** [QCrBox/QCrBox#120]
_Copied from @Niolon's  [comment](https://github.com/QCrBox/QCrBox/issues/120#issuecomment-1964230442) below (for better visibility):_

The QCrBoxTools python library serves a dual purpose here. On one hand it provides building blocks for other containers by either providing the implementation (via the robots) or building blocks for cif handling. On the other hand it provides implementations for problems in a pipeline workflow (at the moment checking convergence, converting isotropic to anisotropic ADPs or converting an arbitrary cif into the unified format QCrBox expects). This pipeline functionality is brought to QCrBox by the QCrBoxTools container.

**Comment by maxalbert** [comment]
Resolved via PR #120.

**Comment by Niolon** [comment]
The QCrBoxTools python library serves a dual purpose here. On one hand it provides building blocks for other containers by either providing the implementation (via the robots) or building blocks for cif handling. On the other hand it provides implementations for problems in a pipeline workflow (at the moment checking convergence, converting isotropic to anisotropic ADPs or converting an arbitrary cif into the unified format QCrBox expects). This pipeline functionality is brought to QCrBox by the QCrBoxTools container.
