### ISSUE TITLE
SHARED_FILES_DIR default not working for me

### ISSUE THREAD

**Issue by mulomulo** [QCrBox/QCrBox#158]
If the SHARED FILE DIR is left at its default value, example_olex2 will not work

QCRBOX_SHARED_FILES_DIR_HOST_PATH=./shared_files/

![image](https://github.com/QCrBox/QCrBox/assets/144746/ff1fcce8-e502-41fa-bedc-40a25de9bef5)

**Comment by Niolon** [comment]
Solved with PRs #162 and #179
