### ISSUE TITLE
Improve interaction between WSL and Windows

### ISSUE THREAD

**Issue by Niolon** [QCrBox/QCrBox#274]
Add instructions to install https://github.com/wslutilities/wslu and setup the environment variable `export BROWSER=wslview` or add via devbox und wsl to enable opening browser windows

**Comment by maxalbert** [comment]
Yeah, we should add this to `devbox.json`. I'm happy to take a stab at it.

**Comment by maxalbert** [comment]
This should be fixed via PR #283. @Niolon let me know if you encounter any remaining issues with this.
