### ISSUE TITLE
Code blocks in dev setup docs are broken

### ISSUE THREAD

**Issue by maxalbert** [QCrBox/QCrBox#280]
<img width="700" alt="Screenshot 2024-09-03 at 17 10 47" src="https://github.com/user-attachments/assets/d25b8aa8-d71e-4b87-9967-07445580b288">

**Comment by maxalbert** [comment]
This is caused by the cookiecutter template folder in `services/applications/_template` because the `docker-compose*.yml` files contain jinja template variables, which makes the yaml parser choke. The solution is to exclude the `_template` folder when looking for `docker-compose*.yml` files.

**Comment by maxalbert** [comment]
Slightly different error now:

<img width="700" alt="Screenshot 2024-10-29 at 10 22 05" src="https://github.com/user-attachments/assets/723920a7-aade-4ebb-a33d-e81616b4c932">

**Comment by Niolon** [comment]
I feel the original should have been solved with PR #330, the new one is probably identical to #368
