### ISSUE TITLE
Fix Jupyterhub setup for example (& playground) notebooks

### ISSUE THREAD

**Issue by maxalbert** [QCrBox/QCrBox#285]
Unfortunately, it looks like the recent fix for the jupyterlab setup inside the devbox shell didn't fully resolve things.
The following steps should make sure it works:
- [ ] Install Jupyterlab as a nix package (`python312Packages.jupyterlab`) to ensure any dependencies that require native libraries are properly resolved.
- [ ] Upon first startup of the devbox shell, install a new IPython kernel from within the qcrbox virtual environment.
- [ ] Generate a jupyterlab config file that specifies this kernel as the default one.
- [ ] Point jupyterlab to the new config when starting up the services.
- [ ] Ensure that the setup steps are only executed once when the devbox shell is first initialised.

**Comment by Niolon** [comment]
Hmm are you sure? I got it to work under WSL with the fix I merged this morning. I only need care to use devbox services stop once before running the example notebooks command

**Comment by maxalbert** [comment]
I eventually got it to work by setting only `LD_LIBRARY_PATH` (on my Linux VM `NIX_LD_LIBRARY_PATH` must **not** be set, otherwise I get different errors).

Fortunately, Devbox just [published](https://github.com/jetify-com/devbox/releases/tag/0.13.0-dev) `0.13.0-dev` (which is a pre-release of the next version). Trying it out (by setting `DEVBOX_USE_VERSION=0.13.0-dev`) this fixes the issues I have seen with `libstdc++.so.6 not found` etc. They write that it is only supported on Linux at the moment (which I assume/hope includes WSL) so at least for Mac we may still need to set `LD_LIBRARY_PATH`/`NIX_LD_LIBRARY_PATH`, but hopefully this will soon be smoothed out too.

**Comment by maxalbert** [comment]
Actually, upon further testing the solution with `LD_LIBRARY_PATH` does _not_ work for me. So it seems the best option is to use devbox version >= `0.13.0-dev` (I added this to the `qcrbox_setup.sh` script in #288).

**Comment by maxalbert** [comment]
@Niolon No rush, but when you have some time could you check whether devbox `0.13.0-dev` also works under WSL2? (You will likely need to remove the environment variables again from `set_env_vars_windows_wsl.sh`).

**Comment by Niolon** [comment]
I have tried it out. It works well'ish. The dev shell is closed quite often but in general does its job

**Comment by maxalbert** [comment]
Thanks for trying it. I'm closing this issue then.

The dev shell closing should be fixed in 531aef7. It was due to the setting `set -e` in one of the scripts that is being sourced when the dev shell is entered because tab completion can trigger a non-zero exit code which causes the shell to close. Let me know if you experience any further problems that are not addressed by this commit.
