### ISSUE TITLE
Build error: "No module named hatchling"

### ISSUE THREAD

**Issue by maxalbert** [QCrBox/QCrBox#335]
@phillybroadbent encountered a build error which I was able to reproduce:
```python
(.venv) (devbox) maxalbert@DESKTOP-KF70IP0:~/code/QCrBox$ qcb build pyqcrbox
Building the following components (including dependencies): pyqcrbox

2024-10-17 10:28:48.285 | INFO     | pyqcrbox.cli.subcommands.build:<lambda>:121 - Building Python package: pyqcrbox
taskid:task_build_python_package:pyqcrbox - TaskError
PythonAction Error
Traceback (most recent call last):
  File "/home/maxalbert/code/QCrBox/pyqcrbox/pyqcrbox/cli/subcommands/build.py", line 76, in action_build_pyqcrbox_wheel
    proc.check_returncode()
  File "/home/maxalbert/code/QCrBox/.devbox/nix/profile/default/lib/python3.12/subprocess.py", line 502, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['/home/maxalbert/code/QCrBox/.venv/bin/hatch', 'build', '-t', 'wheel', '/home/maxalbert/code/QCrBox/services/base_images/base_ancestor/pyqcrbox_dist']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/maxalbert/code/QCrBox/.venv/lib/python3.12/site-packages/doit/action.py", line 461, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxalbert/code/QCrBox/pyqcrbox/pyqcrbox/cli/subcommands/build.py", line 79, in action_build_pyqcrbox_wheel
    raise QCrBoxSubprocessError(error_msg)
pyqcrbox.cli.helpers.qcrbox_helpers.QCrBoxSubprocessError: An error occurred when executing the following command:

    /home/maxalbert/code/QCrBox/.venv/bin/hatch build -t wheel /home/maxalbert/code/QCrBox/services/base_images/base_ancestor/pyqcrbox_dist

Return code: 1

Captured stdout:

                ────────────────────────────────────────────────────────────────────────────── wheel ──────────────────────────────────────────────────────────────────────────────


Captured stderr:

                Setting up build environment
                /home/maxalbert/.local/share/hatch/env/virtual/pyqcrbox/CI7Whp9K/pyqcrbox-build/bin/python: No module named hatchling
```

**Comment by maxalbert** [comment]
@phillybroadbent is still experiencing this issue even though the fix resolved it for me, so I'm reopening it.

**Comment by phillybroadbent** [comment]
I'm getting the same error after running 'qcb build qcrboxtools' on a VirtualBox VM with Ubuntu 24.04.  For info, I installed QCrBox according to the setup instructions here: https://qcrbox.github.io/QCrBox/how_to_guides/set_up_a_dev_environment/ 
![Screenshot from 2024-10-21 10-51-17](https://github.com/user-attachments/assets/f6c7c7ac-cad9-4569-a811-cf2cd6687192)

**Comment by maxalbert** [comment]
I was able to narrow this down to an issue with `hatch` itself. Here is the behaviour that I observe. Starting from a fresh Ubuntu 24.04 VM with docker installed and the QCrBox repo cloned (but no other commands run yet):

- `cd pyqcrbox`
- Run `hatch version` --> the above error occurs (`No module named hatchling`)
- Run `hatch version` again --> the command now succeeds

When `hatch version` is run for the first time, it appears to create an isolated virtual environment and somehow runs the command from there. I'm not sure exactly why this is or why hatchling is missing from this environment. I also don't understand why the command succeeds the second time around.

In any case, for the time being the best solution seems to be to avoid running `hatch version` altogether during the docker build. Since it is only used to determine the version of the pyqcrbox package, we can leverage `setuptools_scm` directly for this.
