### ISSUE TITLE
Demo UI Backend Dependency 3 - Add Data From Docker To The Data Store

### ISSUE THREAD

**Issue by StephenPooley** [QCrBox/QCrBox#349]
Backend - When receiving the "stop ineractive session" request, get data from docker container and add to datastore. And return file ID back to front end.
It is assumed that the user will always name the Olex2 output file as "output.cif". This is a user limitation that will need to be discussed with the end users and modified to behaviour as per the to be decided rules.

**Comment by maxalbert** [comment]
This now works as expected (barring a fix for #402). There is no limitation on the name of the output file - instead, it always returns the newest cif file.
